
name: Daily Earnings Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8AM UTC (1AM PST)
  workflow_dispatch:

jobs:
  update-earnings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: pip install requests

    - name: Run Scraper
      run: python scrape_tradingview_earnings.py

    - name: Commit and Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add mock_upcoming_earnings.json
        git commit -m "Auto-update earnings JSON"
        git push
