name: Update Earnings JSON

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run fetch script
        run: python fetch_optionslam_earnings.py

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add upcoming_earnings.json
          git commit -m "Update upcoming earnings JSON" || echo "No changes to commit"
          git push
