name: Update Earnings JSON

on:
  schedule:
    - cron: '0 1 * * *'  # 每日凌晨 UTC 1:00 執行（即香港時間早上9點）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script to fetch earnings
        run: python fetch_tradingview_earnings.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add mock_upcoming_earnings.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update earnings JSON"
          git push
