name: Update Earnings JSON

on:
  schedule:
    - cron: '0 1 * * *'  # 每日美股收市後 UTC 1AM 執行（即美西下午6點 PDT）
  workflow_dispatch:     # 允許手動觸發

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run Python script to fetch earnings
        run: python fetch_earnings.py

          - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add mock_upcoming_earnings.json

          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -m "Update earnings JSON"
            git push
          fi
