name: Update Earnings JSON

on:
  schedule:
    - cron: '30 23 * * 1-5'  # 每週一到五美東時間 23:30 (即美股收市後)
  workflow_dispatch:  # 手動啟動也可以

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python script to fetch earnings
        run: python fetch_earnings.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add mock_upcoming_earnings.json
          git commit -m 'Update earnings JSON automatically' || echo "No changes to commit"
          git push
